### ISSUE TITLE
About t5_loss

### ISSUE THREAD

**Issue by NanAlbert** [FoundationVision/GenerateU#2]
Thank you for your fascinating work. I noticed in the code that `t5_loss` is not included in the `weight_dict`, which implies that `t5_loss` does not get optimized, meaning the T5 model does not get updated. Is this an oversight, or is there a specific reason for this configuration?

**Comment by clin1223** [comment]
The t5_loss does not require additional weight adjustments, so it is not included in the weight_dict. However, it is still present in the loss_dict and will be optimized within the model.

**Comment by NanAlbert** [comment]
Thank you!
